name: ioos-metrics
channels:
  - conda-forge
dependencies:
  - python=3.12
  - bs4
  - ckanapi
  - eccodes
  - fiscalyear
  - geopandas>=0.13.2
  - jinja2
  - jupyter
  - lxml
  - owslib
  - pandas
  - pdbufr
  - pdfminer.six
  - pyarrow
  - pytest
  - requests
  - suds
