name: ioos-metrics
channels:
  - conda-forge
dependencies:
  - python=3.12
  - bs4
  - ckanapi
  - fake-useragent
  - fiscalyear
  - geopandas>=0.13.2
  - gliderpy
  - html5lib
  - joblib
  - lxml
  - pandas
  - pdfminer.six
  - pyarrow
  - pytest
  - pyobis
  - requests
  - suds
